# Generated by Django 3.2.3 on 2021-06-01 17:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceanswer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_answer',
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='answer',
            field=models.CharField(max_length=1024, null=True, verbose_name='вариант ответа'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True, verbose_name='ответ')),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='ответы')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.question', verbose_name='вопрос')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
